import { beforeAll, describe, expect, it } from 'vitest';
import type { C4ModelSource } from './model';
import { flattenModel } from './model';
import { loadWorkspaceJson } from './test-fixtures';
import type { McpLogger } from './tools';
import {
    listProjectsHandler,
    parseToolResult,
    readElementHandler,
    readProjectSummaryHandler,
    searchElementHandler,
} from './tools';

const FIXTURE = 'simple-workspace';
const PROJECT_URI = 'file:///main.dsl';

function mockSource(model: any, projects: string[] = [PROJECT_URI]): C4ModelSource {
    return {
        listProjects: async () => projects,
        getContent: async (uri: string) => (uri === PROJECT_URI ? model : null),
    };
}

let workspaceJson: any;
let source: C4ModelSource;

beforeAll(async () => {
    workspaceJson = await loadWorkspaceJson(FIXTURE);
    source = mockSource(workspaceJson);
});

describe('MCP tools (from simple-workspace DSL fixture)', () => {
    it('list-projects returns project URIs', async () => {
        const result = parseToolResult(await listProjectsHandler(source));
        expect(result.projects).toEqual([PROJECT_URI]);
    });

    it('read-project-summary aggregates counts', async () => {
        const model = flattenModel(PROJECT_URI, workspaceJson);
        const result = parseToolResult(await readProjectSummaryHandler(source, {}));
        expect(result.project.uri).toBe(PROJECT_URI);
        expect(result.elementCount).toBe(4);
        expect(result.elementsByType).toMatchObject({ Person: 1, SoftwareSystem: 1, Container: 2 });
        // Relationship count includes implied relationships generated by the model.
        const expectedRelationships = model.elements.reduce((n, e) => n + e.relationships.length, 0);
        expect(result.relationshipCount).toBe(expectedRelationships);
        expect(result.viewCount).toBe(model.views.length);
    });

    it('search-element finds by name and by tag', async () => {
        const byName = parseToolResult(await searchElementHandler(source, { search: 'database' }));
        expect(byName.results).toHaveLength(1);
        expect(byName.results[0].name).toBe('Database');

        const byTag = parseToolResult(await searchElementHandler(source, { search: 'Tag1' }));
        expect(byTag.results).toHaveLength(1);
        expect(byTag.results[0].name).toBe('Web Application');
    });

    it('read-element returns element details and included views', async () => {
        const model = flattenModel(PROJECT_URI, workspaceJson);
        const webApp = model.elements.find(e => e.name === 'Web Application')!;
        const result = parseToolResult(await readElementHandler(source, { id: webApp.id }));
        expect(result.element.name).toBe('Web Application');
        expect(result.element.type).toBe('Container');
        const containerView = model.views.find(v => v.type === 'container')!;
        expect(result.includedInViews).toEqual(
            expect.arrayContaining([{ key: containerView.key, type: 'container' }]),
        );
    });

    it('read-element returns error for unknown id', async () => {
        const result = parseToolResult(await readElementHandler(source, { id: '999' }));
        expect(result.error).toBeTruthy();
    });

    it('read-element returns error when project has no model', async () => {
        const emptySource = mockSource(null);
        const result = parseToolResult(await readElementHandler(emptySource, { id: '1' }));
        expect(result.error).toBeTruthy();
    });

    it('handlers emit info events to an optional logger', async () => {
        const events: { level: string; data: unknown }[] = [];
        const logger: McpLogger = (level, data) => { events.push({ level, data }); };
        await readProjectSummaryHandler(source, {}, logger);
        expect(events.map((e) => e.level)).toEqual(['info', 'info']);
    });

    it('handlers emit a warning when the model is missing', async () => {
        const events: { level: string; data: unknown }[] = [];
        const logger: McpLogger = (level, data) => { events.push({ level, data }); };
        const emptySource = mockSource(null);
        await readProjectSummaryHandler(emptySource, {}, logger);
        expect(events.some((e) => e.level === 'warning')).toBe(true);
    });
});
